version: '3.7'
services:
    nginx:
        image: nginx:1.16-alpine
        container_name: nginx-http-status
        volumes:
            - ./imports/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./imports/nginx/index.html:/usr/share/nginx/html/index.html
            - ./imports/nginx/styles.css:/usr/share/nginx/html/styles.css
            - ./imports/data:/data/nginx/cache
        ports:
            - 8080:80